/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#191c1e",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed-variant": "#1d438e",
        "on-primary": "#ffffff",
        "outline-variant": "#c4c6d3",
        "on-surface": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed-variant": "#1b4b68",
        "surface-tint": "#395ca7",
        "on-primary-container": "#7d9eee",
        "outline": "#747782",
        "secondary-fixed": "#d4e3ff",
        "primary-fixed": "#dae2ff",
        "surface-container-low": "#f2f4f6",
        "success-tint": "#2559bd",
        "on-tertiary-container": "#7aa5c6",
        "on-surface-variant": "#434651",
        "tertiary": "#002438",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#b8c7e2",
        "on-primary-fixed": "#001946",
        "background": "#f7f9fb",
        "tertiary-container": "#023b57",
        "primary": "#001e52",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "on-secondary-container": "#56657c",
        "inverse-surface": "#2d3133",
        "error": "#ba1a1a",
        "tertiary-fixed": "#c9e6ff",
        "on-secondary-fixed-variant": "#39485e",
        "error-red": "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-primary": "#b1c5ff",
        "on-tertiary-fixed": "#001e2f",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "secondary": "#505f76",
        "surface-container": "#eceef0",
        "primary-container": "#00327d",
        "surface": "#f7f9fb",
        "on-secondary-fixed": "#0c1c30",
        "tertiary-fixed-dim": "#a0ccee",
        "surface-dim": "#d8dadc",
        "primary-fixed-dim": "#b1c5ff",
        "secondary-container": "#d4e3ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        lg: "32px",
        md: "24px",
        xs: "8px",
        sm: "16px",
        xl: "48px",
        "container-max": "440px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-xs": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
